### Chapter 3 - Unit 1. Numpy

In [20]:
import  numpy  as  np 
import  math 

In [21]:
arr1 = np.array([1,3,5,7,9])

arr1 ,  type(arr1)

(array([1, 3, 5, 7, 9]), numpy.ndarray)

In [22]:
arr2 = np.array([1,3,5,7,9])

arr2 ,  type(arr2)

(array([1, 3, 5, 7, 9]), numpy.ndarray)

In [24]:
id(arr1) , id(arr2)

(1393369712752, 1393370305552)

In [25]:
arr3 = arr1 

arr3 , id(arr3)

(array([1, 3, 5, 7, 9]), 1393369712752)

In [26]:
arr1, arr3 

(array([1, 3, 5, 7, 9]), array([1, 3, 5, 7, 9]))

In [28]:
arr3[4] = 100

arr1 , arr3

(array([  1,   3,   5,   7, 100]), array([  1,   3,   5,   7, 100]))

In [33]:
arr4 = arr1.copy() 

arr4[4] = 200

arr1 , arr4

(array([  1,   3,   5,   7, 100]), array([  1,   3,   5,   7, 200]))

In [39]:
i = 4
print( id(arr1) , id(arr3) )
print(i ,id(arr1[i]) , id(arr3[i]) , id(arr1[i]) == id(arr3[i]))

1393369712752 1393369712752
4 1393376056752 1393376056752 True


In [40]:
tp = (1,3,5,7,9)
tp , type(tp)

((1, 3, 5, 7, 9), tuple)

In [43]:
lst = [1,3,5,7,9]
lst , type(lst)

([1, 3, 5, 7, 9], list)

In [44]:
lst.append(100)

lst

[1, 3, 5, 7, 9, 100]

In [46]:
tplCongDan = ("1112", "A Phủ", 1900, "11 DBP, Gia Lai", "Nam")

tplCongDan, type(tplCongDan)

(('1112', 'A Phủ', 1900, '11 DBP, Gia Lai', 'Nam'), tuple)

In [48]:
# dict - từ điển 

tudien = { 
          "one": "một", 
          "two": "hai", 
          "three" : "ba"
          }

tudien, type(tudien)

({'one': 'một', 'two': 'hai', 'three': 'ba'}, dict)

In [54]:
tudien["four"] = "bốn" 

tudien 

{'one': 'một', 'two': 'hai', 'three': 'ba', 'four': 'bốn'}

In [58]:
"ten"  in tudien

False