## Bài tập --> 7:00  

Tìm và tra bảng lứa tuổi ra độ tuổi:

"thiếu nhi" --> (4,15)  
"nhi đồng" --> (4-9)  
"thiếu niên" --> (10-15)  

thanh thiếu niên  
thanh niên  
trung niên  
"lão"  

--> Tạo từ điển dict cho bảng tra này 

In [2]:
dotuoi = {
    "thiếu nhi" : (4, 15) ,
    "nhi đồng" : (4, 9) , 
    "thiếu niên" : (10, 15) ,
    "thanh niên" : (16, 30) ,
    "thành niên" : (31, 44) , # trưởng thành
    "trung niên" : (45, 60) ,
    "cao niên" : (61,100)
}

dotuoi 

{'thiếu nhi': (4, 15),
 'nhi đồng': (4, 9),
 'thiếu niên': (10, 15),
 'thanh niên': (16, 30),
 'thành niên': (31, 44),
 'trung niên': (45, 60),
 'cao niên': (61, 100)}

In [3]:
# Tập hợp 

taphopsochan = {0,2,4,6,8,10,2,2,2,6,6,6}

taphopsochan

{0, 2, 4, 6, 8, 10}

In [4]:
thsole = {1,3,5,5,5,7,7,9,9}

thsole

{1, 3, 5, 7, 9}

In [8]:
taphopsochan - thsole

{0, 2, 4, 6, 8, 10}

In [9]:
taphopsochan.union(thsole)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [10]:
taphopsochan.intersection(thsole)

set()

In [11]:
taphopsochan.difference(thsole)

{0, 2, 4, 6, 8, 10}

In [12]:
taphopsochan ^ thsole

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [13]:
import  numpy as np 

In [14]:
## Range 

r = range(10)
print(1, r, type(r))

r = list(range(10))
print(2, r, type(r))

r = np.arange(10)
print(3, r, type(r))

1 range(0, 10) <class 'range'>
2 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>
3 [0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [15]:
r1 = np.arange(1, 10)
r2 = np.arange(1, 10, 2)

r1 , r2

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

In [16]:
len(r1) , r1.size , r1.shape  

(9, 9, (9,))

In [18]:
r4 = np.array([11, 5.6 , True, False])

In [19]:
type(r4) , type(r4[3])

(numpy.ndarray, numpy.float64)

In [20]:
r5 = np.array([11, 5.6 , True, False, "mrTu"])

r5 , type(r5), type(r5[2])

(array(['11', '5.6', 'True', 'False', 'mrTu'], dtype='<U32'),
 numpy.ndarray,
 numpy.str_)

In [22]:
## linspace 

l1 = np.linspace(0, 10, 5)
print(1, l1)

l2 = np.linspace(0, 10, 6)
print(2,l2)



1 [ 0.   2.5  5.   7.5 10. ]
2 [ 0.  2.  4.  6.  8. 10.]


In [24]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
m2 = np.ones((2,3,2))
m2 

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [31]:
m2.ndim , m2.shape 

(3, (2, 3, 2))

In [32]:
m3 = np.array([[[1., 2.],
        [3., 4.],
        [5., 6.]],

       [[7., 8.],
        [9., 10.],
        [11., 12.]]])
m3.ndim,  m3.shape, m3

(3,
 (2, 3, 2),
 array([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],
 
        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]]))

In [33]:
m3.reshape(12)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [35]:
m3.reshape(4,3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [45]:
## Random 
snn = np.random.randn(30,30)

In [46]:
snn.mean()

0.005371407830836784

In [49]:
ppd = np.random.rand(100)

In [50]:
ppd.mean()

0.47667486502062817

## 1. nêu các ý tưởng về đề tài sẽ làm cuối khóa 
--> 9:00 ()

## 2. làm tiếp logic của 4 số, ..
--> 9:00 --> hướng dẫn 