# chương 2 - phần 4,5

In [1]:
import  numpy  as np 

In [2]:
A = np.array([[1,-4],[-4,1]])
B = np.array([[1,-8],[-8,2]])

A, B 

(array([[ 1, -4],
        [-4,  1]]),
 array([[ 1, -8],
        [-8,  2]]))

In [3]:
A+B 

array([[  2, -12],
       [-12,   3]])

In [5]:
A-(1/2)*B

array([[0.5, 0. ],
       [0. , 0. ]])

In [6]:
5*A 

array([[  5, -20],
       [-20,   5]])

In [7]:
A.transpose()

array([[ 1, -4],
       [-4,  1]])

In [9]:
C = A*B 
C

array([[ 1, 32],
       [32,  2]])

In [10]:
D = np.array([[1,2,3],[4,5,6]])
D

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
D.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
A.dot(B)

array([[ 33, -16],
       [-12,  34]])

In [13]:
A02 = np.array([[2,3,1],[4,5,1]])
B02 = np.array([[-1,2],[4,-2],[3,6]])

A02, B02 

(array([[2, 3, 1],
        [4, 5, 1]]),
 array([[-1,  2],
        [ 4, -2],
        [ 3,  6]]))

In [14]:
A02.dot(B02)

array([[13,  4],
       [19,  4]])

In [15]:
B02.dot(A02)

array([[ 6,  7,  1],
       [ 0,  2,  2],
       [30, 39,  9]])

In [17]:
A03 = np.array([[1,3],[5,7]])
B03 = np.array([[4,-6],[-8,12]])

A03,B03

(array([[1, 3],
        [5, 7]]),
 array([[ 4, -6],
        [-8, 12]]))

In [18]:
np.linalg.det(A03)  ,  np.linalg.det(B03)  

(-7.999999999999998, 0.0)

In [19]:
ivA03 = np.linalg.inv(A03)
ivA03

array([[-0.875,  0.375],
       [ 0.625, -0.125]])

In [20]:
ivA03 * A03 

array([[-0.875,  1.125],
       [ 3.125, -0.875]])

In [21]:
ivA03.dot(A03)

array([[1., 0.],
       [0., 1.]])

In [22]:
A03.dot(ivA03)

array([[1., 0.],
       [0., 1.]])

## củng cố kỹ năng lập trình python

In [28]:
# câu lệnh thực thi dựa trên điều kiện khác nhau 

so = int( input("Nhập vào một số nguyên: ") ) 

if so % 2 == 0:
    print(so, "la so chan")
else:
    print(so, "la so le")

333 la so le


In [33]:
## vòng lặp, thực hiện nhóm câu lệnh nhiều lần 
import  random 

SoCuaComputer = random.randint(1,99) 

SoLan = 1
while SoLan <= 5:
    SoNguoiDoan = int( input("Nhập vào số bạn đoán (1..99): ")) 
    print("Bạn vừa đoán là số ", SoNguoiDoan)
    if SoNguoiDoan < SoCuaComputer:
        print(" .. số này nhỏ hơn số của Computer")
    elif SoNguoiDoan > SoCuaComputer:
        print(" .. số này LỚN hơn số của Computer")
    else:
        break 
    SoLan += 1 
    
if SoNguoiDoan == SoCuaComputer:
    print("Bạn Thắng, đã đoán trúng ", SoNguoiDoan)
else:
    print("Bạn đã thua !!! số của computer là ", SoCuaComputer)

Bạn vừa đoán là số  50
 .. số này LỚN hơn số của Computer
Bạn vừa đoán là số  30
 .. số này nhỏ hơn số của Computer
Bạn vừa đoán là số  45
 .. số này LỚN hơn số của Computer
Bạn vừa đoán là số  37
 .. số này nhỏ hơn số của Computer
Bạn vừa đoán là số  42
Bạn Thắng, đã đoán trúng  42


## Bài toán Logic đoán số 4 chữ số ABCD 

In [41]:
import  random  

SoCuaComputer = random.randint(0, 9999)

DSChuSo = np.zeros(4)

DSChuSo[0] = SoCuaComputer // 1000
DSChuSo[1] = (SoCuaComputer % 1000) // 100
DSChuSo[2] = (SoCuaComputer % 100) // 10
DSChuSo[3] = SoCuaComputer % 10

print(DSChuSo)


SoNguoiDoan = int( input("Nhập vào số bạn đoán (0..9999): ") )

DSChuSoNguoiDoan = np.zeros(4)

DSChuSoNguoiDoan[0] = SoNguoiDoan // 1000
DSChuSoNguoiDoan[1] = (SoNguoiDoan % 1000) // 100
DSChuSoNguoiDoan[2] = (SoNguoiDoan % 100) // 10
DSChuSoNguoiDoan[3] = SoNguoiDoan % 10

print(DSChuSoNguoiDoan)



[7. 9. 4. 2.]
[4. 5. 6. 7.]
